### ISSUE TITLE
Why are the values in the table inconsistent

### ISSUE THREAD

**Issue by mydoto** [subspace/incentivized-testnets#2]
In [Final_farming_rewards.csv,](https://github.com/subspace/incentivized-testnets/blob/main/Final_farming_rewards.csv) 

`the reward value for each address `

is equivalent to 
the following in [Subspace Testnet Token Distribution List_calculations_FINAL.xlsx](https://github.com/subspace/incentivized-testnets/blob/main/Subspace%20Testnet%20Token%20Distribution%20List_calculations_FINAL.xlsx): 

`sum (Gemini 1, Gemini 2-1, Gemini 2-2, Gemini 3f, gemini 3g, Gemini 3H Pool 1, Gemini 3H Pool 2) `

However, 
it is not equal to 
the last column in Subspace Testnet Token Distribution List_calculations_FINAL.xlsx file: 

`Total amount of token in all testnets `

Why? 
Which value is the mainnet points that the Farm address will eventually get in the mainnet？

**Comment by zkaxin** [comment]
I seem to have made a mistake, I misread it, sorry
